### ISSUE TITLE
Add Gatsby’s new WordPress integration to the existing site

### ISSUE THREAD

**Issue by olavea** [olavea/snoopy-ears-1.0#23]
Add Gatsby’s new WordPress integration to the existing site. These are the tasks you can follow:

Install and activate both of the following plugins in a live WordPress instance.

WPGraphQL
WPGatsby

yarn add gatsby-source-wordpress
In the gatsby-config.js of the starter you just set up, update the plugin options for gatsby-source-wordpress. Change the url option so that it points to your WordPress instance GraphQL url. This should be the full url of your GraphQL endpoint. Eg https://yoursite.com/graphql

Does it work?
yarn develop
go to http://localhost:8000/___graphql

```
query MyQuery {
  allWpPost {
    nodes {
      title
      slug
      content
      tags {
        nodes {
          name
        }
      }
    }
  }
}


{
  "data": {
    "allWpPost": {
      "nodes": [
        {
          "title": "Good Mooorning Werlin!",
          "slug": "hei-verden",
          "content": "<p>WPGatsby is great!</p>\n<p>Who is Werlin?</p>\n<p>Welcome to my test blog for....
        }
      ]
    }
  },
  "extensions": {}
} 

```

These are the step-by-step tiny-tasks you can follow:

Install and activate the WPGraphQL plugin in a live WordPress instance.

![100DaysOfGatsby-day-50-task-23-WP-WPGraphQL-62](https://user-images.githubusercontent.com/7642493/108592621-0fe28680-736f-11eb-94b9-ebad580efb24.jpg)
![100DaysOfGatsby-day-50-task-23-WP-WPGraphQL-63](https://user-images.githubusercontent.com/7642493/108592633-1cff7580-736f-11eb-9d00-7a483f2dd2b3.jpg)
![100DaysOfGatsby-day-50-task-23-WP-WPGraphQL-64](https://user-images.githubusercontent.com/7642493/108592655-31437280-736f-11eb-8cb9-f6997401c7d5.jpg)

Install and activate the WPGatsby plugin in a live WordPress instance.

![100DaysOfGatsby-day-51-task-23-WP-WPGatsby-72](https://user-images.githubusercontent.com/7642493/108592978-33a6cc00-7371-11eb-8309-1d23e81fd62b.jpg)
![100DaysOfGatsby-day-50-task-23-WP-WPGatsby-67](https://user-images.githubusercontent.com/7642493/108592985-428d7e80-7371-11eb-9ed5-ee82b3d2d9cc.jpg)

**Comment by olavea** [comment]
https://www.wpgraphql.com/docs/quick-start/
query {
  posts {
    nodes {
      title
    }
  }
}


WPGatsby
![100DaysOfGatsby-day-50-task-23-WP-WPGatsby-67](https://user-images.githubusercontent.com/7642493/108480699-9166e580-7297-11eb-8a79-f5c6144d9642.jpg)

   {
     resolve: `gatsby-source-wordpress`,
     options: {
       url: `http://olavea.com/graphql`,
       url:  `https://snoopy-ears.wpgraphql.com/graphql`,
     },
   },

**Comment by olavea** [comment]
ERROR 

HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/Users/olavea/Desktop/Develop/100days/snoopy-ears-1.0/snoopy-ears-1.0/node_modules/gatsby-source-wordpress/node_modules/got
/dist/source/core/index.js:896:31)
    at Request._onResponse (/Users/olavea/Desktop/Develop/100days/snoopy-ears-1.0/snoopy-ears-1.0/node_modules/gatsby-source-wordpress/node_modules/got/dis
t/source/core/index.js:931:24)
    at ClientRequest.<anonymous> (/Users/olavea/Desktop/Develop/100days/snoopy-ears-1.0/snoopy-ears-1.0/node_modules/gatsby-source-wordpress/node_modules/g
ot/dist/source/core/index.js:945:23)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit
(/Users/olavea/Desktop/Develop/100days/snoopy-ears-1.0/snoopy-ears-1.0/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at HTTPParser.execute (<anonymous>)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: undefined,
  timings: {
    start: 1613724750506,
    socket: 1613724750506,
    lookup: 1613724750507,
    connect: 1613724750558,
    secureConnect: undefined,
    upload: 1613724750558,
    response: 1613724750623,
    end: 1613724750626,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 51,
      tls: undefined,
      request: 0,
      firstByte: 65,
      download: 3,
      total: 120
    }
  }
}

⠀
warn  gatsby-source-wordpress  Error occurred while fetching media item in step:

"Creating File node from URL where we couldn't find a MediaItem node"

Edit link: http://olavea.com/wp-admin/post.php?post=2977&action=edit
File url: http://olavea.com/wp-includes/js/tinymce/plugins/wordpress/img/trans.gif

This error will fail production builds.
⠀

**Comment by olavea** [comment]
Where to get these?
```
{
        accessToken: process.env.GATSBY_Wp_ACCESS_TOKEN,
        spaceId: process.env.GATSBY_Wp_SPACE_ID,
      },
```

**Comment by olavea** [comment]
http://olavea.com/wp-includes/js/tinymce/plugins/wordpress/img/trans.gif
